[package]
name = "grab_links"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crunchyroll-rs = "0.10"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
